version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - ireturn
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - cyclop
    - depguard
    - forbidigo
    - funlen
    - gochecknoglobals
    - goconst
    - godox
    - lll
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - paralleltest
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/twpayne/go-pinentry)
    gofumpt:
      module-path: github.com/twpayne/go-pinentry
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/twpayne/go-pinentry
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
