name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
        - stable
        - oldstable
      fail-fast: false
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - name: build
      run: go build ./...
    - name: test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@82d40c283aeb1f2b6595839195e95c2d6a49081b
      with:
        version: v1.54.2